export type DisplayScreen =
  | 'Actions'
  | 'Deliver Form'
  | 'Dashboard'
  | 'Home'
  | 'Passcode'
  | 'Settings'
  | 'Delivery dashboard'
  | 'Room number'
  | 'Delivery message'
  | 'Delivery summary'
  | 'Favorites'
  | 'Multiple select favorites'
  | 'Utilities'
  | 'CancelTask'
  | 'CancelTaskConfirmation'
  | 'Search'
  | 'Status'
  | 'Help'
  | 'Mapping'
  | 'Mapping Choice'
  | 'Override Map'
  | 'Create Map'
  | 'GoToSearch';
