export const styles = {
  eyesContainer: {
    width: '40%',
    display: 'flex',
    justifyContent: 'space-between',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    backgroundImage: `url(/images/robot-ui-background.jpg)`,
    backgroundSize: 'cover',
    minHeight: '100vh',
  },
  messageContainer: {
    minWidth: '1060px',
    position: 'relative',
    marginBottom: 7,
  },
  paper: {
    minHeight: '400px',
    height: '100%',
    display: 'flex',
    borderRadius: '20px',
    borderBottom: '5px solid white',
    flexDirection: 'column',
    padding: 2,
    '&::after': {
      content: "''",
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: -49,
      margin: '0 auto',
      width: 0,
      height: 0,
      borderTop: '50px solid white',
      borderLeft: '20px solid transparent',
      borderRight: '20px solid transparent',
    },
  },
  button: {
    // height: '65px',
    width: '373px',
  },
};
