export const styles = {
  eyesContainer: {
    overflow: 'hidden',
    display: 'flex',
    justifyContent: 'space-between',
    // alignItems: 'center',
    maxHeight: '50%',
    width: '50%',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    height: '100%',
  },
  messageContainer: {
    minWidth: '90%',
    position: 'relative',
    marginBottom: 7,
  },
  paper: {
    minHeight: '400px',
    height: '100%',
    display: 'flex',
    borderRadius: '20px',
    borderBottom: '5px solid white',
    flexDirection: 'column',
    padding: 2,
    '&::after': {
      content: "''",
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: -49,
      margin: '0 auto',
      width: 0,
      height: 0,
      borderTop: '50px solid white',
      borderLeft: '20px solid transparent',
      borderRight: '20px solid transparent',
    },
  },
};
