export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    position: 'relative',
    height: '100%',
    '&::after': {
      content: "''",
      position: 'absolute',
      left: 0,
      right: '81%',
      bottom: -40,
      margin: '0 auto',
      width: 0,
      height: 0,
      borderBottom: '50px solid white',
      borderLeft: '35px solid transparent',
    },
  },
  messageContainer: {
    width: '80%',
    minWidth: '1137px',
    position: 'relative',
  },
  paper: {
    height: '600px',
    padding: 2,
    marginBottom: -5,
    borderRadius: '20px',
    display: 'flex',
  },
  leftSideTextContainer: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    marginRight: 5,
    marginLeft: 3,
    marginTop: 6,
  },
  leftSideContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  rightSideContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    justifyContent: 'flex-end',
  },
  button: {
    height: '65px',
    width: '350px',
    fontSize: '24px',
  },
  confirmTextContainer: {
    marginBottom: 2,
  },
  messageTextContainer: {
    width: '75%',
  },
  gridItem: {
    display: 'flex',
  },
  summaryTextContainer: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
  },
  summaryText: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
};
