name: pr-close
on:
  pull_request:
    types: [closed]

jobs:
  aptly_remove:
    runs-on: ubuntu-latest
    steps:
      - name: Find this PRs Focal packages
        run: |
          echo "DEL_FOCAL_PACKAGES=$(curl --user ${{ secrets.APTLY_USER }}:${{ secrets.APTLY_PASSWD }} https://aptly.savioke.com/api/repos/savioke-focal/packages?q=${{ github.event.repository.name }}-pr.${{ github.event.number }})" >> $GITHUB_ENV
      - name: Delete this PRs Focal packages
        run: |
          curl --user ${{ secrets.APTLY_USER }}:${{ secrets.APTLY_PASSWD }} -X DELETE -H 'Content-Type: application/json' --data "{\"PackageRefs\": ${DEL_FOCAL_PACKAGES}}" https://aptly.savioke.com/api/repos/savioke-focal/packages

